name: build

on:
  push:
    branches:
    - brln_windows_deployment_fix

jobs:
  build:
    name: Build Stage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install ALSA/Jack - Ubuntu
      run: sudo apt-get update -y; sudo apt-get install -y libjack-dev libasound2-dev
      if: matrix.os == 'ubuntu-latest'
    - name: Install Jack - macOS
      run: brew install jack
      if: matrix.os == 'macos-latest'
    - name: Make Build Directory
      run: mkdir build
    - name: Configuration
      run: cmake ..
      working-directory: ./build
    - name: Build
      run: cmake --build . --target rtaudio
      working-directory: ./build
    # Upload artifacts
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-artifacts
        path: ./build/
